### ISSUE TITLE
No operations defined in spec!

### ISSUE THREAD

**Issue by orkenstein** [aaronestrada/flask-restplus-swagger-relative#1]
I use `Flast-Restplus` behind k8s Nginx Ingress.
After I setup the module as described, I get in browser:
```
No operations defined in spec!
```
'cause the location of `swagger.json` is wrong: 
http://domain.com/swagger.json instead of->   http://domain.com/this_is_a_new/path_for_swagger/swagger.json

**Comment by aaronestrada** [comment]
This problem should be fixed in the release v0.1. I had developed it time ago but I never uploaded the newest version. Please check if this problem persists.

https://github.com/aaronestrada/flask-restplus-swagger-relative/releases/tag/v0.1

**Comment by orkenstein** [comment]
@aaronestrada thanks!
Could you please also make a pypi release, so I can install it on remote.

**Comment by aaronestrada** [comment]
@orkenstein you're welcome!

There is no need of creating the pypi release, you can add the following line in your requirements.txt to install it:
git+https://git@github.com/aaronestrada/flask-restplus-swagger-relative.git@v0.1

Or via pip:
$ pip install git+https://git@github.com/aaronestrada/flask-restplus-swagger-relative.git@v0.1

**Comment by orkenstein** [comment]
@aaronestrada, so I've tried this:
```
# ---------------------------------------------------------
# App setup
# ---------------------------------------------------------
app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app)
# ---------------------------------------------------------
# Swagger docs
# ---------------------------------------------------------
api = FlaskRestplusRelativeSwaggerApi(app )
# Option 2: set Swagger specs in documentation generation with no scheme
api.set_external_swagger_specs(external=False)
api_doc = FlaskRestplusRelativeSwagger()
api_doc.init_app(app=app, url='/some-path/')
# ---------------------------------------------------------
```
 which gives me this:
<img width="641" alt="Screen Shot 2019-10-31 at 00 37 30" src="https://user-images.githubusercontent.com/1461936/67901584-32e49800-fb78-11e9-9810-cd208c730e80.png">

Looks like `swagger.json` is still the problem:
<img width="364" alt="Screen Shot 2019-10-31 at 00 37 48" src="https://user-images.githubusercontent.com/1461936/67901799-bdc59280-fb78-11e9-8863-35e1ef1c34c0.png">

But `swagger.json` actually at `dev.domain.com/some-path/swagger.json`.

Am I missing something?

**Comment by aaronestrada** [comment]
@orkenstein you also need to specify the path for the FlaskRestplusRelativeSwaggerApi instance. If you don't, then the default path will be '/', and swagger.json will be deployed there.

To specify such path, you can use a Blueprint, passing it then to the FlaskRestplusRelativeSwaggerApi instead of using directly the Flask instance:

```python
# ---------------------------------------------------------
# App setup
# ---------------------------------------------------------
app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app)
# ---------------------------------------------------------
# Swagger docs
# ---------------------------------------------------------
api_blueprint = Blueprint("MyBlueprint", __name__, url_prefix="/some-path")

# Use api_blueprint instead of app to set prefix
api = FlaskRestplusRelativeSwaggerApi(api_blueprint)

# Register Blueprint in application
app.register_blueprint(api_blueprint)

# Option 2: set Swagger specs in documentation generation with no scheme
api.set_external_swagger_specs(external=False)

api_doc = FlaskRestplusRelativeSwagger()
api_doc.init_app(app=app, url='/some-path/')
# ---------------------------------------------------------
```

Let me know if it works.

**Comment by orkenstein** [comment]
@aaronestrada, thanks for your quick replies!
But... no luck.
Probably, you misunderstood my setup:
I have a Nginx Ingress Controller on k8s. It uses single Load balancer on some IP to serve multiple APIs.
The base path is http://dev.domain.com. The flask-based API (with failing swagger) is proxied with ingress rule at http://dev.domain.com/some-path. The swagger must be available at this path.
The pure **flask-restplus** setup gives me this kind of errors:
```JS
ReferenceError: Can't find variable: SwaggerUIBundle
```
I guess, because the browser can't find SwaggerUI with Nginx proxy. Then, if I add:
```python
api_doc = FlaskRestplusRelativeSwagger()
api_doc.init_app(app=app, url='/some-path/')
```
The above error disappears, BUT the `swagger.json` path at `/some-path/` JavaScript is wrong:
```JS
            const ui = window.ui = new SwaggerUIBundle({
                url: "/swagger.json",
```
Instead of `/some-path/swagger.json`. So, SwaggerUI fails to load spec:
<img width="641" alt="Screen Shot 2019-10-31 at 00 37 30" src="https://user-images.githubusercontent.com/1461936/67937547-d5cffd00-fbde-11e9-9b4b-e96f86f657d5.png">

Then if I add:
```python
api_blueprint = Blueprint("MyBlueprint", __name__, url_prefix="/some-path")

# Use api_blueprint instead of app to set prefix
api = FlaskRestplusRelativeSwaggerApi(api_blueprint)

# Register Blueprint in application
app.register_blueprint(api_blueprint)
```
The doc path now http://dev.domain.com/some-path/some-path, and (surprise!) spec is not accessible again:
```js
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
```js
            const ui = window.ui = new SwaggerUIBundle({
                url: "/some-path/swagger.json",
```
Again, physically it's at http://dev.domain.com/some-path/some-path.json
This is some kinda puzzle I can't solve 😸

**Comment by aaronestrada** [comment]
@orkenstein could you post your ingress? I also publish my APIs in K8S with NGINX, I think the problem is there since the swagger.json file is published correctly using the Blueprint.

**Comment by orkenstein** [comment]
> @orkenstein could you post your ingress? I also publish my APIs in K8S with NGINX, I think the problem is there since the swagger.json file is published correctly using the Blueprint.

But `swagger.json` is published incorrectly with Blueprint:
Physically at `/some-path/some-path/swagger.json`
           vs. at JS `/some-path/swagger.json`.

**Comment by aaronestrada** [comment]
> But `swagger.json` is published incorrectly with Blueprint:
> Physically at `/some-path/some-path/swagger.json`
> vs. at JS `/some-path/swagger.json`.

Because the ingress adds the first "/some-path", so there must be a problem there, not in the application.

**Comment by orkenstein** [comment]
@aaronestrada anyway, my ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  creationTimestamp: "2019-09-10T10:30:24Z"
  generation: 16
  name: dev-ingress
  namespace: default
  resourceVersion: "51661581"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/dev-ingress
  uid: 000eef9a-d3b6-11e9-89e9-42010af00070
spec:
  rules:
  - host: dev.domain.com
    http:
      paths:
      - backend:
          serviceName: the-api
          servicePort: 80
        path: /some-path/?(.*)
status:
  loadBalancer:
    ingress:
    - ip: <address>
```

**Comment by orkenstein** [comment]
> > But `swagger.json` is published incorrectly with Blueprint:
> > Physically at `/some-path/some-path/swagger.json`
> > vs. at JS `/some-path/swagger.json`.
> 
> Because the ingress adds the first "/some-path", so there must be a problem there, not in the application.

The whole api gets shifted with Blueprint, not only `swagger.json`

**Comment by aaronestrada** [comment]
> The whole api gets shifted with Blueprint, not only `swagger.json`

Yes, but it is because the ingress shifts everything with the "rewrite-target" annotation. 

Try removing the rewrite like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  creationTimestamp: "2019-09-10T10:30:24Z"
  generation: 16
  name: dev-ingress
  namespace: default
  resourceVersion: "51661581"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/dev-ingress
  uid: 000eef9a-d3b6-11e9-89e9-42010af00070
spec:
  rules:
  - host: dev.domain.com
    http:
      paths:
      - backend:
          serviceName: the-api
          servicePort: 80
        path: /some-path
status:
  loadBalancer:
    ingress:
    - ip: <address>
```

**Comment by orkenstein** [comment]
@aaronestrada I need rewrite for other backend services, which needs it to function properly.
UPDATE:
Without rewrite flask-swagger works fine

**Comment by aaronestrada** [comment]
> @aaronestrada I need rewrite for other backend services, which needs it to function properly.
> UPDATE:
> Without rewrite flask-swagger works fine

Excellent!

In this case I would suggest you to create an ingress without rewrite for this service, keeping the other one with the rest of services.

**Comment by orkenstein** [comment]
Finally, it can be done in single ingress with rewrite:
```yaml
annotations:
  kubernetes.io/ingress.class: nginx-internal
  nginx.ingress.kubernetes.io/rewrite-target: /$1
...
path: "/(some-path.*)"
```
